#!/usr/bin/env tsx

/*
 * AUTO-GENERATED by `pnpm gen:publish-commands` for v5.1.
 *
 * One `npm publish` per publishable package. Comment out the lines that
 * already published, raise DELAY_MS if you keep hitting HTTP 429, then run:
 *   tsx packages/v5.1/scripts/publish-commands.mts
 *
 * Re-running is safe: an already-published version just logs an error and is
 * skipped. Regenerate this file with `pnpm gen:publish-commands` at any time.
 */

import * as path from 'node:path';
import { Result } from 'ts-data-forge';
import { $ } from 'ts-repo-utils';

/** Pause between publishes (ms). Increase if you still hit 429. */
const DELAY_MS = 5000;

const versionRoot = path.resolve(import.meta.dirname, '..');

const sleep = (ms: number): Promise<void> =>
  new Promise((resolve) => {
    setTimeout(resolve, ms);
  });

const publishPkg = async (pkgName: string): Promise<void> => {
  const cmd = `npm publish ${pkgName} --access public --registry=https://registry.npmjs.org/`;
  console.info(`$ ${cmd}`);
  const result = await $(cmd, { cwd: versionRoot });
  if (Result.isErr(result)) {
    console.error(`  FAILED: ${result.value.message.split('\
').slice(0, 3).join(' ')}`);
  }
  await sleep(DELAY_MS);
};

await publishPkg('output-branded/lib');
await publishPkg('output-branded/packages/decorators');
await publishPkg('output-branded/packages/decorators/legacy');
await publishPkg('output-branded/packages/dom');
await publishPkg('output-branded/packages/dom/iterable');
await publishPkg('output-branded/packages/es2015');
await publishPkg('output-branded/packages/es2015/collection');
await publishPkg('output-branded/packages/es2015/core');
await publishPkg('output-branded/packages/es2015/generator');
await publishPkg('output-branded/packages/es2015/iterable');
await publishPkg('output-branded/packages/es2015/promise');
await publishPkg('output-branded/packages/es2015/proxy');
await publishPkg('output-branded/packages/es2015/reflect');
await publishPkg('output-branded/packages/es2015/symbol');
await publishPkg('output-branded/packages/es2015/symbol/wellknown');
await publishPkg('output-branded/packages/es2016');
await publishPkg('output-branded/packages/es2016/array/include');
await publishPkg('output-branded/packages/es2016/full');
await publishPkg('output-branded/packages/es2017');
await publishPkg('output-branded/packages/es2017/full');
await publishPkg('output-branded/packages/es2017/intl');
await publishPkg('output-branded/packages/es2017/object');
await publishPkg('output-branded/packages/es2017/sharedmemory');
await publishPkg('output-branded/packages/es2017/string');
await publishPkg('output-branded/packages/es2017/typedarrays');
await publishPkg('output-branded/packages/es2018');
await publishPkg('output-branded/packages/es2018/asyncgenerator');
await publishPkg('output-branded/packages/es2018/asynciterable');
await publishPkg('output-branded/packages/es2018/full');
await publishPkg('output-branded/packages/es2018/intl');
await publishPkg('output-branded/packages/es2018/promise');
await publishPkg('output-branded/packages/es2018/regexp');
await publishPkg('output-branded/packages/es2019');
await publishPkg('output-branded/packages/es2019/array');
await publishPkg('output-branded/packages/es2019/full');
await publishPkg('output-branded/packages/es2019/intl');
await publishPkg('output-branded/packages/es2019/object');
await publishPkg('output-branded/packages/es2019/string');
await publishPkg('output-branded/packages/es2019/symbol');
await publishPkg('output-branded/packages/es2020');
await publishPkg('output-branded/packages/es2020/bigint');
await publishPkg('output-branded/packages/es2020/date');
await publishPkg('output-branded/packages/es2020/full');
await publishPkg('output-branded/packages/es2020/intl');
await publishPkg('output-branded/packages/es2020/number');
await publishPkg('output-branded/packages/es2020/promise');
await publishPkg('output-branded/packages/es2020/sharedmemory');
await publishPkg('output-branded/packages/es2020/string');
await publishPkg('output-branded/packages/es2020/symbol/wellknown');
await publishPkg('output-branded/packages/es2021');
await publishPkg('output-branded/packages/es2021/full');
await publishPkg('output-branded/packages/es2021/intl');
await publishPkg('output-branded/packages/es2021/promise');
await publishPkg('output-branded/packages/es2021/string');
await publishPkg('output-branded/packages/es2021/weakref');
await publishPkg('output-branded/packages/es2022');
await publishPkg('output-branded/packages/es2022/array');
await publishPkg('output-branded/packages/es2022/error');
await publishPkg('output-branded/packages/es2022/full');
await publishPkg('output-branded/packages/es2022/intl');
await publishPkg('output-branded/packages/es2022/object');
await publishPkg('output-branded/packages/es2022/regexp');
await publishPkg('output-branded/packages/es2022/sharedmemory');
await publishPkg('output-branded/packages/es2022/string');
await publishPkg('output-branded/packages/es2023');
await publishPkg('output-branded/packages/es2023/array');
await publishPkg('output-branded/packages/es2023/full');
await publishPkg('output-branded/packages/es5');
await publishPkg('output-branded/packages/es6');
await publishPkg('output-branded/packages/esnext');
await publishPkg('output-branded/packages/esnext/full');
await publishPkg('output-branded/packages/esnext/intl');
await publishPkg('output-branded/packages/scripthost');
await publishPkg('output-branded/packages/webworker');
await publishPkg('output-branded/packages/webworker/importscripts');
await publishPkg('output-branded/packages/webworker/iterable');
await publishPkg('output/lib');
await publishPkg('output/packages/decorators');
await publishPkg('output/packages/decorators/legacy');
await publishPkg('output/packages/dom');
await publishPkg('output/packages/dom/iterable');
await publishPkg('output/packages/es2015');
await publishPkg('output/packages/es2015/collection');
await publishPkg('output/packages/es2015/core');
await publishPkg('output/packages/es2015/generator');
await publishPkg('output/packages/es2015/iterable');
await publishPkg('output/packages/es2015/promise');
await publishPkg('output/packages/es2015/proxy');
await publishPkg('output/packages/es2015/reflect');
await publishPkg('output/packages/es2015/symbol');
await publishPkg('output/packages/es2015/symbol/wellknown');
await publishPkg('output/packages/es2016');
await publishPkg('output/packages/es2016/array/include');
await publishPkg('output/packages/es2016/full');
await publishPkg('output/packages/es2017');
await publishPkg('output/packages/es2017/full');
await publishPkg('output/packages/es2017/intl');
await publishPkg('output/packages/es2017/object');
await publishPkg('output/packages/es2017/sharedmemory');
await publishPkg('output/packages/es2017/string');
await publishPkg('output/packages/es2017/typedarrays');
await publishPkg('output/packages/es2018');
await publishPkg('output/packages/es2018/asyncgenerator');
await publishPkg('output/packages/es2018/asynciterable');
await publishPkg('output/packages/es2018/full');
await publishPkg('output/packages/es2018/intl');
await publishPkg('output/packages/es2018/promise');
await publishPkg('output/packages/es2018/regexp');
await publishPkg('output/packages/es2019');
await publishPkg('output/packages/es2019/array');
await publishPkg('output/packages/es2019/full');
await publishPkg('output/packages/es2019/intl');
await publishPkg('output/packages/es2019/object');
await publishPkg('output/packages/es2019/string');
await publishPkg('output/packages/es2019/symbol');
await publishPkg('output/packages/es2020');
await publishPkg('output/packages/es2020/bigint');
await publishPkg('output/packages/es2020/date');
await publishPkg('output/packages/es2020/full');
await publishPkg('output/packages/es2020/intl');
await publishPkg('output/packages/es2020/number');
await publishPkg('output/packages/es2020/promise');
await publishPkg('output/packages/es2020/sharedmemory');
await publishPkg('output/packages/es2020/string');
await publishPkg('output/packages/es2020/symbol/wellknown');
await publishPkg('output/packages/es2021');
await publishPkg('output/packages/es2021/full');
await publishPkg('output/packages/es2021/intl');
await publishPkg('output/packages/es2021/promise');
await publishPkg('output/packages/es2021/string');
await publishPkg('output/packages/es2021/weakref');
await publishPkg('output/packages/es2022');
await publishPkg('output/packages/es2022/array');
await publishPkg('output/packages/es2022/error');
await publishPkg('output/packages/es2022/full');
await publishPkg('output/packages/es2022/intl');
await publishPkg('output/packages/es2022/object');
await publishPkg('output/packages/es2022/regexp');
await publishPkg('output/packages/es2022/sharedmemory');
await publishPkg('output/packages/es2022/string');
await publishPkg('output/packages/es2023');
await publishPkg('output/packages/es2023/array');
await publishPkg('output/packages/es2023/full');
await publishPkg('output/packages/es5');
await publishPkg('output/packages/es6');
await publishPkg('output/packages/esnext');
await publishPkg('output/packages/esnext/full');
await publishPkg('output/packages/esnext/intl');
await publishPkg('output/packages/scripthost');
await publishPkg('output/packages/webworker');
await publishPkg('output/packages/webworker/importscripts');
await publishPkg('output/packages/webworker/iterable');
